services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: clist-server
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-C8i4Z8KRbVMN/MRdL/UFZk0zu4A6V/8TVnQrMyxYKEU=}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-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}
      - USE_AI_SERVER=${USE_AI_SERVER:-false}
      - NODE_SERVER_URL=${NODE_SERVER_URL:-https://clist-ai-server.onrender.com}